project:
  type: website

website:
  title: "BC Children's Research MRI Wiki"
  image: /img/banner.png
  favicon: /img/magnet.png
  announcement:
    # icon: info-circle
    dismissable: true
    content: "🎉 Join our Mattermost server and follow us on Bluesky"
    type: primary
    position: below-navbar
  repo-url: https://github.com/BCCH-MRI-Research-Facility/BCCH-MRI-Research-Facility.github.io
  repo-actions: [edit, source, issue]
  back-to-top-navigation: true
  open-graph: true #improve the previews of your content when a link to it is pasted into applications like Slack, Discord, Facebook, Linkedin, and more
  sidebar:
    style: "docked"
    search: true
    contents: auto
  navbar:
    logo: /img/magnet.png
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/bcch-mri-research.bsky.social
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/BCCH-MRI-Research-Facility/BCCH-MRI-Research-Facility.github.io
          - text: Report a Bug
            href: https://github.com/BCCH-MRI-Research-Facility/BCCH-MRI-Research-Facility.github.io/issues
  google-analytics: "G-B9X9W6319W"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

