project:
  type: website

website:
  open-graph: true #improve the previews of your content when a link to it is pasted into applications like Slack, Discord, Facebook, Linkedin, and more
  search:
    location: navbar
    type: overlay
  title: "BCCH MRI Research Facility Github Page"
  sidebar:
    style: "docked"
    search: true
    contents: auto
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/BCCH-MRI-Research-Facility/BCCH-MRI-Research-Facility.github.io
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  google-analytics: "G-B9X9W6319W"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

