project:
  type: website

website:
  title: "BCCH MRI Research Facility Github Page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

